language: python
matrix:
    include:
        - python: 3.8
          dist: bionic
        - python: 3.8
          arch: arm64
          dist: bionic 
before_install:
  - sudo apt-get install nodejs; node --version
install:
  - pip install -U coverage requests six websocket-client
  - npm install -G socket.io@1
  - pip install invisibleroads-macros
before_script:
  - DEBUG=* node socketIO_client/tests/serve.js &
  - sleep 1
script: nosetests
